# Generated by Django 3.1.1 on 2020-09-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckreditor_example', '0002_auto_20200918_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postckeditor',
            name='body',
        ),
        migrations.RemoveField(
            model_name='postckeditor',
            name='order',
        ),
    ]
